Add Bolivia national shields
osm-americana/openstreetmap-americana pull request #1172
Opened 2024-11-26 11:26 UTC by whubsch

This pull requests adds road shields for Bolivia's national route network. I can't find any evidence that these shields are used on the ground, but they are used in cartographic representations of the road network. National legislation also outlines designs for departmental and municipal route shields (see below), but I can't find any evidence that those are used in any context.

I've chosen just to reuse the green US interstate business route shield for simplicity's sake.

![Screenshot 2024-10-15 at 5 55 50 AM](https://github.com/user-attachments/assets/2d25aec9-7526-40da-9e0c-99d58d4c6469)

[localhost link](http://localhost:1776/#map=10.47/-17.9538/-67.0857)
![Screenshot 2024-11-26 at 6 10 18 AM](https://github.com/user-attachments/assets/a939762d-feaf-4737-9ab7-0985794ab115)

[departmental map of Oruro](https://www.abc.gob.bo/wp-content/uploads/2018/08/MAPA_ORURO_2018.pdf)
![Screenshot 2024-11-26 at 6 10 29 AM](https://github.com/user-attachments/assets/99879992-3092-4cdf-9874-4cd660558715)

2024-11-27 16:35 UTC, quincylvania commented
It seems like the US route shield would be a better fit than the interstate shield? There is a function to set the color without adding another sprite.

2024-11-30 03:03 UTC, ZeLonewolf requested changes
Thanks for the PR.  I agree that a badge shield (like the ones used in the US Numbered Highway System) is the right style for this network.

2024-11-30 22:23 UTC, whubsch commented on src/js/shield_defs.js
> +  shields["BO:fundamental"] = shields["US:I:Business:Loop"];
Handy, didn't realize that was a possibility. Latest commit should use the generic `badgeShieldCrossbar` icon:

<img width="532" alt="Screenshot 2024-11-30 at 5 17 15 PM" src="https://github.com/user-attachments/assets/d428ada5-0879-4d31-bb0f-0d8a4ecb912c">

2024-11-30 22:24 UTC, whubsch commented
Thanks for the suggestions! The latest commit should use the generic `badgeShieldCrossbar` icon.

2024-11-30 22:41 UTC, ZeLonewolf approved these changes
Looks great!  Thanks for the contribution.

2024-11-30 22:41 UTC, merged